add_library(icuuc STATIC
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/appendable.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/bmpset.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/brkeng.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/brkiter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/bytesinkutil.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/bytestream.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/bytestriebuilder.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/bytestrie.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/bytestrieiterator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/caniter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/characterproperties.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/chariter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/charstr.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/cmemory.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/cstr.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/cstring.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/cwchar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/dictbe.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/dictionarydata.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/dtintrv.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/edits.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/errorcode.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/filteredbrk.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/filterednormalizer2.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/icudataver.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/icuplug.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/loadednormalizer2impl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/locavailable.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/locbased.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/locdispnames.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/locdspnm.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/locid.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/loclikely.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/locmap.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/locresdata.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/locutil.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/messagepattern.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/normalizer2.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/normalizer2impl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/normlzr.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/parsepos.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/patternprops.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/pluralmap.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/propname.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/propsvec.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/punycode.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/putil.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/rbbi_cache.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/rbbi.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/rbbidata.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/rbbinode.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/rbbirb.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/rbbiscan.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/rbbisetb.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/rbbistbl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/rbbitblb.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/resbund_cnv.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/resbund.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/resource.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ruleiter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/schriter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/serv.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/servlk.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/servlkf.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/servls.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/servnotf.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/servrbf.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/servslkf.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/sharedobject.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/simpleformatter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/static_unicode_sets.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/stringpiece.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/stringtriebuilder.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uarrsort.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ubidi.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ubidiln.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ubidi_props.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ubiditransform.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ubidiwrt.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ubrk.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucasemap.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucasemap_titlecase_brkiter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucat.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uchar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucharstriebuilder.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucharstrie.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucharstrieiterator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uchriter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucln_cmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucmndata.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnv2022.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnv_bld.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnvbocu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnv_cb.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnv_cnv.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnv.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnv_ct.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnvdisp.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnv_err.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnv_ext.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnvhz.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnv_io.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnvisci.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnvlat1.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnv_lmb.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnvmbcs.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnvscsu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnvsel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnv_set.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnv_u16.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnv_u32.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnv_u7.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucnv_u8.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucol_swp.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucptrie.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ucurr.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/udata.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/udatamem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/udataswp.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uenum.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uhash.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uhash_us.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uidna.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uinit.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uinvchar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uiter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ulist.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uloc.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uloc_keytype.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uloc_tag.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/umapfile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/umath.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/umutablecptrie.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/umutex.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/unames.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/unifiedcache.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/unifilt.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/unifunct.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uniset_closure.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uniset.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uniset_props.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/unisetspan.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/unistr_case.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/unistr_case_locale.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/unistr_cnv.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/unistr.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/unistr_props.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/unistr_titlecase_brkiter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/unormcmp.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/unorm.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uobject.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uprops.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uresbund.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ures_cnv.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uresdata.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/usc_impl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uscript.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uscript_props.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uset.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/usetiter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uset_props.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ushape.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/usprep.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ustack.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ustrcase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ustrcase_locale.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ustr_cnv.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ustrenum.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ustrfmt.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ustring.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ustr_titlecase_brkiter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ustrtrns.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/ustr_wcs.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/utext.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/utf_impl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/util.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/util_props.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/utrace.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/utrie2_builder.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/utrie2.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/utrie.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/utrie_swap.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uts46.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/utypes.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uvector.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uvectr32.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/uvectr64.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common/wintz.cpp
)

target_compile_definitions(icuuc PRIVATE
    U_COMMON_IMPLEMENTATION=1
    ${ICU_COMPILE_DEFINITIONS}
)

target_compile_options(icuuc PRIVATE
    -Wno-error
    -Wno-shorten-64-to-32
)

target_include_directories(icuuc PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/common
    ${CMAKE_CURRENT_SOURCE_DIR}/icu4c/source/i18n
)
